<a href="https://colab.research.google.com/github/joshua031903/TEAM-2-Major-Project/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
d=pd.read_csv('Churn_Modelling.csv')
X=d.iloc[:, 3:-1].values
y=d.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:, 2]=le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [ ]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [ ]:
ann=tf.keras.models.Sequential()


In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
ann.fit(X_train,y_train,batch_size=32, epochs=20)

Epoch 1/20
250/250 [==============================] - 2s 4ms/step - loss: 0.6070 - accuracy: 0.6741
Epoch 2/20
250/250 [==============================] - 1s 4ms/step - loss: 0.4648 - accuracy: 0.7962
Epoch 3/20
250/250 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.8001
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8102
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4106 - accuracy: 0.8245
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8324
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3876 - accuracy: 0.8395
Epoch 8/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3781 - accuracy: 0.8453
Epoch 9/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3702 - accuracy: 0.8504
Epoch 10/20
250/250 [==============================] - 1s 3ms/step - loss: 0.3649 - accuracy: 0.8512

In [ ]:
y_pred=ann.predict(X_test)
y_pred=y_pred>0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 1s 6ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1543   52]
 [ 221  184]]


0.8635